version: '3.3'

services:

  todo-db:
    container_name: todo-db
    image: mcr.microsoft.com/mssql/server
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "Password123" -Q "SELECT 1"
      interval: 10s
      timeout: 15s
      retries: 5
      start_period: 30s
    environment:
      - ACCEPT_EULA="Y"
      - MSSQL_SA_PASSWORD="Password123"
    ports:
      - 1444:1433

  todo-api:
    build:
      context: .
      target: development
    environment:
       - ASPNETCORE_ENVIRONMENT="Development"
       - ASPNETCORE_URLS="http://+:80"
    ports:
      - 1445:80
    develop:
      watch:
        - action: rebuild
          path: .
    depends_on:
      todo-db:
        condition: service_healthy

networks:

  default:
    name: todo-net
