version: '3.4'

services:
  webapi:
    image: sammykirigha/comply-test-api
    build:
      context: ./TodoApi/
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    container_name: comply-test-api
    hostname: comply-test-api
    restart: unless-stopped
  
  ui:
    image: sammykirigha/comply-test-ui
    build:
      context: ./TodoUi/
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    expose:
      - 80
    depends_on:
      - webapi
    container_name: comply-test-ui
    networks:
      - comply-test-network

networks:
  comply-test-network:
    driver: bridge