version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-preview-ubuntu-22.04
    environment:
        - ACCEPT_EULA=Y
        - MSSQL_SA_PASSWORD=ComplyTest2024@1234
        - UID=10001
        - GID=10001
        - MSSQL_PID:Evaluation
    ports:
        - "14333:1433"
    container_name: comply-test-sqlserver
    hostname: comply-test-sqlserver
    restart: unless-stopped
    volumes:
        - sqlVolume:/var/opt/mssql
    
volumes:
  sqlVolume: